# Copyright 2023 flochre
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ranges2scan_params.yaml
/:
  ranges2scan:
    ros__parameters:
      # this is the frame id where the data will be converted to via TF
      # this frame_id should be link to your range sensors
      # you can also use the base_link if you want
      frame_id: laser_frame

      # this is the list of topics that the package will convert into the scan
      range_sensor_topics:
        - /uss_sensor_broadcaster/range
        - /uss_front_broadcaster/range
        - /uss_right_broadcaster/range
        # Add more range sensor topics as needed
